### ISSUE TITLE
영화 상영관 타입 정리

### ISSUE THREAD

**Issue by changhwa** [codechobostudy/movie-api#10]
Enum aggregate 정도로 생각하면 될 거 같긴한데요.
몇몇분이 같이 써야할 거 같아서 해당 이슈에서 의논 후 위키에 정리할 예정입니다.

ScreenType
- 3d
- 4d
- screenX
- imax

우선은 이정도만 지정했으면 싶은데 추가 의견 있으신가요?

**Comment by iamkyu** [comment]
`2d`도 필요하지 않을까요?

**Comment by changhwa** [comment]
OK
