### ISSUE TITLE
16.08.21 스터디 시간 회의할 내용

### ISSUE THREAD

**Issue by changhwa** [codechobostudy/movie-api#18]
- [x] 패키지 구조 논의 
- [x] 테스트 커버리지 이야기 : 70%
- [x] Merge : 우선 @changhwa

**Comment by changhwa** [comment]
패키지구조 1안

```
application
domain
infrastructure
interfaces
```

패키지구조 2안

```
(기능명)
   - service
   - dto
   - infra
   - model
```

패키지구조 3안

```
 (기능명)
   - application
   - domain
   - infrastructure
   - interfaces
```

**Comment by changhwa** [comment]
전 3안에 한표 !

**Comment by loustler** [comment]
각 패키지 구조에 대해서 설명이 있었으면 좋겠습니다 :)

패키지의 의도와 간단한 몇몇 예시 등등이요

**Comment by changhwa** [comment]
@dongyeonlee 
https://github.com/changhwa/tdd-example/tree/master/src/main/java/io/pretense

application 은 최상단 레이어로 가장 고수준 인터페이스들이 정의되거나 배치 config 트랜잭션 등등..
domain 은 말그대로 도메인정의 및 Repository 가 정의가 되구요
infrastructure 는 대부분 일반적인 서비스를 생각하면 여기가 맞을 듯하고요.
interfaces 는 controller라 보시면 될거같네요.

**Comment by loustler** [comment]
@changhwa 감사합니다 :) 

1안과 2안이 적절히 섞인 3안이 좋은 것 같습니다

**Comment by iamkyu** [comment]
저도 3안에 한표

**Comment by reiphiel** [comment]
저도 3안이 좋을 것 같습니다. 패키지 명 자체는 2안이 익숙한 느낌이긴 하지만 DDD적으로는 3안이 맞을 듯 합니다.

**Comment by changhwa** [comment]
과반수로 3안으로...
