### ISSUE TITLE
16.09.04 회의 

### ISSUE THREAD

**Issue by changhwa** [codechobostudy/movie-api#30]
- [x] 주간 소감 공유

**Comment by loustler** [comment]
`enum` type의 패키지 구조에 대해서 논의가 필요한 것 같습니다.

**Comment by changhwa** [comment]
저같은경우는 domain aggrgate로 판단하여 도메인 패키지에 넣고는 있습니다

**Comment by loustler** [comment]
저도 `enum`은 `domain`하위에 넣어놨어요
